let edad: number;
let altura: number = 1.72;
let nombre: string = "Calificador1";
let mayor_edad: boolean = false;
let genero: string;
edad = 17;
genero = 'H';
console.log("Bienvenido: " + nombre + " su altura es de: " + altura + " metros y tiene: " + edad + " años");
let nota_1: number, nota_2: number = 61, nota_3: number = 80, nota_4: number;
let nombre_1: string = "Cali2", nombre_2: string, nombre_3: string;
let isTree: boolean, isApple: boolean = false, isMountain: boolean;
let inicial: string = 'A', final: string;
let sueldo_base: number = 1250.25, sueldo_neto: number, igss: number, cobro_iva: number = 12.0;
console.log("Nota_1 = " + nota_1);
console.log("Nota_2 = " + nota_2);
console.log("Nota_3 = " + nota_3);
console.log("Nota_4 = " + nota_4);
console.log("nombre_1 = " + nombre_1);
console.log("nombre_2 = " + nombre_2);
console.log("nombre_3 = " + nombre_3);
console.log("isTree: " + isTree);
console.log("isApple: " + isApple);
console.log("isMountain: " + isMountain);
console.log("Sueldo base = " + sueldo_base);
console.log("Sueldo neto = " + sueldo_neto);
console.log("IGSS = " + igss);
console.log("Cobro IVA = " + cobro_iva);
